---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptpad-helm.fullname" . }}
  labels:
    {{- include "cryptpad-helm.labels" . | nindent 4 }}
data:
  config.js: |
    /* globals module */

    module.exports = {
          httpUnsafeOrigin: '{{ include "cryptpad-helm.mainDomain" . | trim }}',
          httpSafeOrigin: '{{ include "cryptpad-helm.sandboxDomain" . | trim }}',

          {{- if .Values.config.adminKeys }}
            adminKeys: [
              {{- range $key := .Values.config.adminKeys }}
                {{ $key | quote }}, 
              {{- end }}
            ],
          {{- else}}
            adminKeys: [],
          {{- end}}

          {{- if .Values.config.maxUploadSize }}
            maxUploadSize: {{.Values.config.maxUploadSize}},
          {{- else}}
          {{- end}}

          {{- range $key, $value := .Values.config }}
            {{- if and (ne $key "httpUnsafeOrigin") (ne $key "httpSafeOrigin") (ne $key "adminKeys") (ne $key "maxUploadSize") }}
              {{- if or (kindIs "bool" $value) (kindIs "float64" $value) (kindIs "int64" $value) }}
              {{ $key }}: {{ $value }},
              {{- else if or (kindIs "slice" $value) (kindIs "map" $value) }}
              {{ $key }}: {{ $value | toJson }},
              {{- else }}
              {{ $key }}: {{ $value | quote }},
              {{- end }}
            {{- end }}
          {{- end }}
        };
  application_config.js: |
    /*
    * You can override the configurable values from this file.
    * The recommended method is to make a copy of this file (/customize.dist/application_config.js)
      in a 'customize' directory (/customize/application_config.js).
    * If you want to check all the configurable values, you can open the internal configuration file
      but you should not change it directly (/common/application_config_internal.js)
    */
    define(['/common/application_config_internal.js'], function (AppConfig) {

        {{- range $key, $value := .Values.application_config }}
          AppConfig.{{ $key }} =  {{ $value | toJson }};
        {{- end }}

        return AppConfig;
    });
